SELECT *
FROM OnlineRetail_Cleaned;

-- Returns and Cancellation Analysis

-- percentage of orders that are cancelled/returned
-- months with the most returns
-- the most returned products

	
	SELECT
		(SELECT COUNT(DISTINCT InvoiceNo)
		 FROM Returns_Transactions) AS Cancelled_Orders,
		(SELECT COUNT(DISTINCT InvoiceNo)
		 FROM Clean_Sales) AS Completed_Orders,
		ROUND(100.0 * 
			(SELECT COUNT(DISTINCT InvoiceNo)
			 FROM Returns_Transactions) 
			 /
			(SELECT COUNT(DISTINCT InvoiceNo)
			 FROM Clean_Sales), 2) AS Cancellation_Percentage;
	
-- from all valid retail transactions, there were 3,590 cancelled/returned transactions totalling 19.37%.
-- this is considerably high for a retail dataset, indicating product satisfaction/expectation mismatch may exist.



	SELECT
		strftime('%Y-%m', InvoiceDate) AS Month,
		COUNT(DISTINCT InvoiceNo) AS Returns
	FROM Returns_Transactions
	WHERE Quantity < 0
	GROUP BY month
	ORDER BY month;

-- most returns are made in the months from October to December, which aligns with the sales volume.
-- this could be due to returns on gifts bought around Christmas time.



	SELECT
		Description,
		SUM(Quantity) AS Quantity_Returned,
		COUNT(DISTINCT InvoiceNo) AS Returns
	FROM Returns_Transactions
	WHERE Quantity < 0 
	AND StockCode NOT IN ('POST', 'M')			-- removes non-physical products
	GROUP BY Description
	ORDER BY Quantity_Returned;					-- ORDER BY Returns DESC 		<--- for returns frequency analysis
	
-- this dataset shows a small number of products accounting for a disproportionately large volume of returns.
-- this is primarily due to bulk returns rather than consistent return behaviour,
-- therefore, return metrics should be interpreted alongside return frequency rather than return volume alone. 
	
	
	


-- Customer Segmentation Analysis

-- highest repeat customers
-- highest value customers by quartile


	SELECT
		Country,
		CustomerID,
		ROUND(SUM(Quantity * UnitPrice), 2) AS Total_Spend,
		SUM(Quantity) AS Total_Products,
		COUNT(DISTINCT InvoiceNo) AS No_of_Orders
	FROM Clean_Sales
	GROUP BY CustomerID
	ORDER BY No_of_Orders DESC;
	
-- most loyal customers are from the UK, however there are some high value customers from abroad.
-- less-valuable customers should be targeted for a loyalty scheme to improve repeat purchasers.

	
	
	SELECT
		CustomerID,
		Total_Spend,
		NTILE(4) OVER (ORDER BY Total_Spend DESC) AS Spend_Quartile
	FROM (
		SELECT
			CustomerID,
			SUM(Quantity * UnitPrice) AS Total_Spend
		FROM Clean_Sales
		GROUP BY CustomerID
	);

-- this model shows structured customer segmentation for business decision making.
-- the top 25% of customers have all spent upwards of £1.6k.
-- the bottom 25% have spent less than £308.





-- Business Recommendations

-- investigate high return/cancellations
	-- the dataset shows a high level of returns/cancellation activity. 
	-- further investigation should be taken to learn the reasoning behind returns.
	-- analysing returns by product category, customer segment or volume may help identify reasons for the issue.
-- develop customer retention strategies
	-- a large proportion of revenue is generated by a small number of customers. 
	-- implementing a loyalty scheme, personalised promotions or targeted marketing may help increase repeat purchasing behaviour.
-- prepare for seasonal demand
	-- sales spike in the final months of the calendar year.
	-- preparing stock for these periods is crucial to improve customer fulfilment.
	

